### ISSUE TITLE
Add Shipit stack for rubygems

### ISSUE THREAD

**Issue by stefanmb** [Shopify/kubernetes-deploy#100]
- https://rubygems.org/profiles/shopify-shipit should be an owner.
- Shipit stack needs to be added, like: https://shipit.shopify.io/shopify/buildkit/rubygems

/cc: @Shopify/cloudplatform  @JonPulsifer

**Comment by JonPulsifer** [comment]
ref https://github.com/Shopify/kubernetes-deploy/pull/99

**Comment by KnVerey** [comment]
This is done. Thanks @stefanmb !
