### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#105]
- [x] Improve readme (better explanation of core functionality and options, screenshots)
- [ ] Convert all existing comment-based docs to rdoc or [yard](http://www.rubydoc.info/gems/yard/file/docs/Tags.md#List_of_Available_Tags)
- [x] Add comment-based docs for the key methods you need to use the tasks from Ruby instead of from the CLI (i.e. the `run` and `run!` methods of each `Task` class).

**Comment by kirs** [comment]
We use yard in Shopify core. Maybe it would make sense to use it here too.

**Comment by KnVerey** [comment]
Ideas for more readme enhancements:

- [ ] Description of a few workflows like:
  - Getting started - using stuff from an 'examples' directory
  - Walk through the steps of a deploy
- [ ] GIF screen recording of terminal running a deploy locally - put this right near the top of the readme

**Comment by KnVerey** [comment]
- [ ] Readme should reference a directory of examples, even if it is just our test fixtures

**Comment by dirceu** [comment]
After https://github.com/Shopify/kubernetes-deploy/pull/581 and https://github.com/Shopify/kubernetes-deploy/pull/582, do we need anything else?

I'm not sure about this:

> Convert all existing comment-based docs to rdoc or yard

There aren't many comments, and most are specific to a particular condition inside a method, etc.

**Comment by KnVerey** [comment]
I'm inclined to agree now that only thing we need to document with yard are the public interfaces.
