### ISSUE TITLE
Revisit supported ruby version

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#134]
We nominally support ruby 2.1 or greater, and have Rubocop set up accordingly. However, it turns out this has not been true since we added the ActiveSupport dependency:

```ruby
activesupport-5.1.1 requires ruby version >= 2.2.2, which is incompatible with the current version, ruby 2.1.8p440
```

Should we:

A) Change the dependency to fall in line with shipit-engine's minimum version as originally intended; or

B) Set an independent, higher requirement.

Given the extent to which we work with variable parsed JSON in this gem, the safe navigation operator introduced in  2.3 would be tremendously useful. And although we certainly designed this gem around Shipit's use case, it isn't all that functionally tied to Shipit. For those reasons, I vote for (B), and making that requirement ruby 2.3.

@Shopify/cloudplatform @kirs

**Comment by kirs** [comment]
👍 for 2.3 as long it's available on Shopify's Shipit setup

**Comment by n1koo** [comment]
👍 for 2.3, I don't see any reason for supporting older versions than what Shipit is using as long as theres no other major users

**Comment by ibawt** [comment]
2.3 sounds fine to me.
