### ISSUE TITLE
Summary section inaccurate when deploy aborted

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#137]
If you kill the deploy somewhere between the initiation and completion of an action, the deploy summary printed will be inaccurate. For example, if you abort the deploy between the predeploy and the main deploy, the summary will say "No actions taken". Ideas for solutions:

1) Introduce a mechanism for tracking the action currently being attempted and reporting it on failure
2) Don't print the summary section when the process has been killed
3) Change the message printed to be more ¯\\\_(ツ)_/¯

**Comment by benlangfeld** [comment]
@KnVerey Should this have been closed by https://github.com/Shopify/kubernetes-deploy/pull/244/files#r177486770 , or is there something else to be done here?

**Comment by dturn** [comment]
#244 definitely implemented (2) . The UX would be better if we'd done (1) but it hasn't come up so I think we can close this out and re-open if it comes up again.
