### ISSUE TITLE
Bad output when scaling Deployment to zero

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#155]
![image](https://user-images.githubusercontent.com/4789493/28834373-0fad6780-76b0-11e7-9204-e931de7f76b6.png)

The Deployment was in fact successfully scaled to zero. The zero-replica integration test deploys zero replicas to begin with; we need one that deploys 1 and then scales to 0 in a second deploy.

**Comment by peiranliushop** [comment]
The originally reported error log could not be reproduced although scale down was successful. A test is added in PR https://github.com/Shopify/kubernetes-deploy/pull/224
If the error logs appear again in future, the test should be able to catch it, then we can reopen the issue.
I will close the issue.
