### ISSUE TITLE
Support CronJob

### ISSUE THREAD

**Issue by tspacek** [Shopify/kubernetes-deploy#166]
With CronJob entering beta in 1.8, it would be great to be able to manage them as a kubernetes-deploy resource

https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/

**Comment by KnVerey** [comment]
We haven't been adding support for alpha resources, but I agree we should support CronJobs once they're Beta. I've added this request to our internal 1.8 upgrade tracker.

**Comment by skaes** [comment]
This has been addressed in #206

**Comment by KnVerey** [comment]
#206 is included in release 0.15.0
