### ISSUE TITLE
Create namespace?

### ISSUE THREAD

**Issue by alexcurtin** [Shopify/kubernetes-deploy#170]
If we include a namespace.yaml in the template dir shouldn't `kubernetes-deploy` be able to create the namespace? We tried that and it did not.

**Comment by KnVerey** [comment]
You're right, it isn't currently capable of creating namespaces; on the contrary, its preliminary validation step includes a check that the namespace already exists. In Shopify's setup, cluster admin tooling creates namespaces for app developers, who can then populate those namespaces by using this gem via Shipit (https://github.com/Shopify/shipit-engine#kubernetes). Our vision is therefore that this gem operates only _within_ a namespace. However, perhaps we could make ns init possible via an override, or conversely enable it by default unless we detect we're running in Shipit. cc @kirs wdyt?

**Comment by alexcurtin** [comment]
Any way we could have a feature or flag passed to it like `kubernetes-deploy --allow-namespace` that lets us utilize the tool to check for existing namespace and create if not exists?

**Comment by dturn** [comment]
Stale. We don't have the resources to work on this, but we'd be willing to accept a PR assuming the namespace resource matches namespace we're deploying to, and a flag would not be required.
