### ISSUE TITLE
Quick fail for ResourceQuota violation

### ISSUE THREAD

**Issue by karanthukral** [Shopify/kubernetes-deploy#173]
## What?
- Currently when a pod/deployment fails because of resource quotas, the gem will timeout and then display the issue
- In such a case the gem should just quick fail since the deploy is doomed

**Comment by KnVerey** [comment]
> In such a case the gem should just quick fail since the deploy is doomed

I'm not so sure about this anymore. Often the cause of quota errors is that they are surging too high, so the effect of the quota ceiling is basically throttling the rollout. I'm leaning towards the timeout being the correct behaviour in the end. @karanthukral wdyt?

**Comment by karanthukral** [comment]
> I'm leaning towards the timeout being the correct behaviour in the end
I agree. Since its not a doomed deploy everytime, its better to timeout 👍
