### ISSUE TITLE
ServiceAccount resources should be predeployed like ConfigMaps

### ISSUE THREAD

**Issue by albertrdixon** [Shopify/kubernetes-deploy#179]
The use case here is attaching a service account to the pre-deploy unmanaged Pods. Currently these pods fail if they have a service account attached since ServiceAccount objects are deployed after unmanaged Pods.

**Comment by KnVerey** [comment]
Seems reasonable to me. @karanthukral, you implemented the SA class; do you agree?

**Comment by karanthukral** [comment]
Seems reasonable. Should be easy to implement!
