### ISSUE TITLE
Dry-run?

### ISSUE THREAD

**Issue by alexcurtin** [Shopify/kubernetes-deploy#182]
Can `kubernetes-deploy` gem support a `dry-run` flag? so before it runs it would test the dry-run as a way to lint your yamls for kubernetes before you deploy for real?

**Comment by KnVerey** [comment]
We actually already run `kubectl create --dry-run` on all the templates before starting the deploy, [here](https://github.com/Shopify/kubernetes-deploy/blob/7da5ab3a76586cc775f6f86d1f9610eb44712c8b/lib/kubernetes-deploy/runner.rb#L186-L195). If that identifies any template as invalid, the deploy will not proceed. Here's an example of what that looks like:

![image](https://user-images.githubusercontent.com/4789493/31032554-71631a08-a52a-11e7-9f7f-0ef9cece6653.png)

Is that sufficient for your use case, or are you hoping to use this dry run flag at a separate stage of your CI/CD?

**Comment by alexcurtin** [comment]
That should be sufficient thanks!

**Comment by airhorns** [comment]
*peep peep* I think that this feature might still be useful for just validating templates before actually triggering a deploy, for example in branches that shouldn't be deployed but will eventually be deployed. My specific use case is that I am porting a bunch of other k8s yaml to `kubernetes-deploy` and I want to know how close I got to what is in production and what would actually change when I run `kubernetes-deploy` for the first time. 

Not a huge deal because it is already run, but I think it would be useful for sure!

**Comment by KnVerey** [comment]
> for just validating templates before actually triggering a deploy

For validating the templates, I'd suggest it would be more effective to use our renderer to generate them and then put them through a purpose-built tool like [kubeval](https://github.com/garethr/kubeval), which can work without access to a cluster (much better for branch CI). We extracted the rendering functionality to its own class a while ago to make things like this possible from Ruby, and I'm definitely open to exposing a `kubernetes-render` command that prints the templates to stdout or something if that would be useful.

> My specific use case is that I am porting a bunch of other k8s yaml to kubernetes-deploy and I want to know how close I got to what is in production and what would actually change when I run kubernetes-deploy for the first time.

Doing a dry run of the deploy could give you information about which resources will change, but still wouldn't tell you whether the details of the resources would change, no? For that you'd need something like `kubectl diff`, which is in alpha in 1.12, entering beta in 1.13: https://github.com/kubernetes/enhancements/issues/491

I'd feel much better about adding a true `--dry-run` flag for the whole deploy process once changes on the Kubernetes side to make the dry runs more accurate and available for all operations have been completed (ref https://github.com/kubernetes/kubernetes/issues/11488).

**Comment by airhorns** [comment]
Ah ha, I see, I didn't know dry-run was so very dry at the moment, and that makes sense that it'd be more worth supporting when it was in line with what `kubernetes-deploy` actually does. 

I will fiddle with the renderer from Ruby land and report back!
