### ISSUE TITLE
Flakey Tests

### ISSUE THREAD

**Issue by stefanmb** [Shopify/kubernetes-deploy#226]
Please add new flakes to [this spreadsheet](https://docs.google.com/spreadsheets/d/16NeL3Q76n1IrRMmHwSJN6UjIKRDM4eABFN2keTjgYTw/edit?usp=sharing)

----
**Original issue**

Based on manual analysis of failed nightly builds:

- test_bad_container_on_stateful_sets_fails_with_rolling_update
    - This test seems 100% broken on k8s 1.9
    - It has also failed on [1.7](https://buildkite.com/shopify/kubernetes-deploy-gem-nightly/builds/64#5ee3391e-c2ea-4d9a-b518-ff9267a5da00)
- test_crashing_container_on_deployment_fails_quickly
   - 1.8 fails sporadically
   - [1.6 fails sporadically](https://buildkite.com/shopify/kubernetes-deploy-gem-nightly/builds/43#ddf287e7-a7a4-43b5-b13f-d4a8f2aa0fc7)
- test_deploy_result_logging_for_mixed_result_deploy
   - 1.8 fails sporadically
   - 1.6 fails sporadically
- test_deployment_with_progress_times_out_for_short_duration
   - 1.8 fails sporadically
- test_output_when_switching_labels_incorrectly
   - 1.6 fails sporadically

**Comment by KnVerey** [comment]
* test_bad_init_container_on_deployment_fails_quickly
  * 1.8 fails sporadically
* test_output_of_failed_unmanaged_pod
  * 1.8 failed once (missing "The following containers encountered errors:")
* test_bad_container_on_daemon_sets_fails
  * all versions fail sporadically [1.6](https://buildkite.com/shopify/kubernetes-deploy-gem/builds/256#29f5826e-643d-4703-8a28-b6bfcd6aabc3), [1.7](https://buildkite.com/shopify/kubernetes-deploy-gem/builds/254#8017159a-87d9-4960-9783-796e54640fe1), [1.8](https://buildkite.com/shopify/kubernetes-deploy-gem-nightly/builds/19#4a398717-8ec7-4192-9a60-8a69fe8585f5) 
* test_restart_failure
  * 1.8 failed [a](https://buildkite.com/shopify/kubernetes-deploy-gem-nightly/builds/11#c33e6320-b207-42c9-ba61-26faf320b688) [couple](https://buildkite.com/shopify/kubernetes-deploy-gem-nightly/builds/5#ca3d0cfb-a804-425c-a6e9-1e4d04238a04) times

**Comment by KnVerey** [comment]
- [ ] test_bad_container_on_stateful_sets_fails_with_rolling_update
- [ ] test_crashing_container_on_deployment_fails_quickly
  * this passed 100 times in a row for me locally against 1.8, taking between 7s and 17s. On CI it fails regularly with a PDS timeout. When it passes, it does so in ~8 seconds, whereas it fails after ~22s.
- [ ] test_deploy_result_logging_for_mixed_result_deploy
- [ ] test_deployment_with_progress_times_out_for_short_duration
- [ ] test_output_when_switching_labels_incorrectly 
- [ ] test_bad_init_container_on_deployment_fails_quickly
- [ ] test_output_of_failed_unmanaged_pod
- [ ] test_bad_container_on_daemon_sets_fails
- [ ] test_restart_failure

**Comment by KnVerey** [comment]
Since I just put a bunch of work into addressing this, I've made a [spreadsheet](https://docs.google.com/spreadsheets/d/16NeL3Q76n1IrRMmHwSJN6UjIKRDM4eABFN2keTjgYTw/edit?usp=sharing) to help us track new flakes after my PR merges.
