### ISSUE TITLE
Detect non-existing secret when mounted as a volume

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#248]
When a template mounts a non-existing secret as an env var, we eagerly detect that and fail the deploy. However,  this detection is not working when it is mounted as a volume.

**Comment by dturn** [comment]
Right now the information needed to detect this is only exposed in events not in the pods status. (Capturing events is far too expensive to do during a deploy). The comment at https://github.com/Shopify/kubernetes-deploy/blob/master/test/integration/kubernetes_deploy_test.rb#L294 is still accurate.

**Comment by KnVerey** [comment]
😢 too bad. Thanks for looking into it.
