### ISSUE TITLE
Replace ejson with ecfg

### ISSUE THREAD

**Issue by joekohlsdorf** [Shopify/kubernetes-deploy#260]
[ecfg](https://github.com/Shopify/ecfg) is a backwards compatible drop-in replacement for `ejson` supporting JSON, YAML and TOML.
Besides nobody liking JSON, YAML just feels more at home in the K8s ecosystem.

If existing, the following files should be deployed as secrets:
* secrets.ejson
* secrets.ecfg.json
* secrets.ecfg.yaml
* secrets.ecfg.yml
* secrets.ecfg.toml

**Comment by klautcomputing** [comment]
We looked into this and asked the author what he thinks about it and he gave as a 👎 for now. He updated the readme with some information on why he thinks it's not a good idea to use it in production yet. Sorry, to be the bearer of bad news. 🙂

**Comment by burke** [comment]
Truth be told, I don't remember the exact issues. I was also working on https://github.com/shopify/ecfg-ruby around the same time, and I know *for sure* that one has several parse/transform issues in YAML and TOML.

It may be the case that `ecfg`'s primary fault is just lacklustre test coverage, in which case, if someone would put in some work to add more proof that it does already work correctly, I'd stop advocating against its use.
