### ISSUE TITLE
Apply sorting to overview outputs

### ISSUE THREAD

**Issue by joekohlsdorf** [Shopify/kubernetes-deploy#261]
I do deployments containing more than 30 resources. With this amount, the output of the overviews is not easily comparable between runs so these don't serve a whole lot.

In my opinion, the following outputs should by alphabetically sorted:
* Discovering templates
* Checking initial resource statuses
* Deploying resources
* Result: Successful resources

**Comment by benlangfeld** [comment]
I'll do this just as soon as https://github.com/Shopify/kubernetes-deploy/pull/424 is merged, because they will conflict.
