### ISSUE TITLE
Services for zero-replica statefulsets time out

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#265]
# Bug report

If you deploy a StatefulSet + Service pair where the SS's replicas is set to zero, the service will eventually time out with a message like this:

```
[FATAL][2018-04-04 18:52:53 +0000]	Service/thing: TIMED OUT (timeout: 420s)
[FATAL][2018-04-04 18:52:53 +0000]	This service does not seem to select any pods. This means its spec.selector is probably incorrect.
[FATAL][2018-04-04 18:52:53 +0000]	  - Final status: Selects 0 pods
[FATAL][2018-04-04 18:52:53 +0000]	  - Events: None found. Please check your usual logging service (e.g. Splunk).
```
We've explicitly handled this for zero-replica deployments, but services can be placed in front of any pod-generating controller.

**Expected behavior:** The deploy recognizes that these services aren't meant to have endpoints and succeeds.

**Actual behavior:** The deploy times out.

**Version(s) affected:** 0.18.0

### Steps to Reproduce

Deploy a StatefulSet + Service pair where the SS's replicas is set to zero

**Comment by KnVerey** [comment]
In fact, the logic we're using for services is flawed and doesn't acknowledge the full range of service types possible. We should revisit it in general.

**Comment by dturn** [comment]
> We've explicitly handled this for zero-replica deployments, but services can be placed in front of any pod-generating controller.

This is true, but sticking a service in front of a CronJob/Job seems unusual enough that I don't think we need to handle this case.
