### ISSUE TITLE
Minimum required version of activesupport is incorrect. Should be >= 5.0

### ISSUE THREAD

**Issue by jpatters** [Shopify/kubernetes-deploy#267]
# Bug report

Added this to a rails 4.2 project and ran it and got this
```
kubernetes-deploy/duration_parser.rb:19:in `rescue in parse!': uninitialized constant ActiveSupport::Duration::ISO8601Parser (NameError)
	from /Users/jordan/.rvm/gems/ruby-2.4.3/gems/kubernetes-deploy-0.18.0/lib/kubernetes-deploy/duration_parser.rb:17:in `parse!'
	from /Users/jordan/.rvm/gems/ruby-2.4.3/gems/kubernetes-deploy-0.18.0/lib/kubernetes-deploy/kubernetes_resource.rb:313:in `validate_timeout_annotation'
	from /Users/jordan/.rvm/gems/ruby-2.4.3/gems/kubernetes-deploy-0.18.0/lib/kubernetes-deploy/kubernetes_resource.rb:81:in `validate_definition'
	from /Users/jordan/.rvm/gems/ruby-2.4.3/gems/kubernetes-deploy-0.18.0/lib/kubernetes-deploy/concurrency.rb:13:in `each'
	from /Users/jordan/.rvm/gems/ruby-2.4.3/gems/kubernetes-deploy-0.18.0/lib/kubernetes-deploy/concurrency.rb:13:in `block (2 levels) in split_across_threads'
```

**Expected behavior:** [What you expected to happen]
It should have run successfully since the minimum active support version in the gemspec is set at >=4.2
**Actual behavior:** [What actually happened]
It failed
**Version(s) affected:** [run `kubernetes-deploy --version`]
0.18.0

I believe this fails because `ActiveSupport::Duration::ISO8601Parser` wasn't added until activesupport 5.0.

**Comment by dturn** [comment]
Thanks for spotting this bug. Looks like ISO8601Parser 
 was added in 5.0 given: http://api.rubyonrails.org/v5.0/classes/ActiveSupport/Duration.html & http://api.rubyonrails.org/v4.2/classes/ActiveSupport/Duration.html. We'll get this fixed up.
