### ISSUE TITLE
Use the default 'RollingUpdate' strategy if type is not set

### ISSUE THREAD

**Issue by jpatters** [Shopify/kubernetes-deploy#268]
# Feature request

The default strategy for replacing old pods is RollingUpdate. Currently, if `spec.strategy.type` is not set, `kubernetes-deploy` fails with
```
'kubernetes-deploy.shopify.io/required-rollout: maxUnavailable' is incompatible with strategy ''
```
when `kubernetes-deploy.shopify.io/required-rollout=maxUnavailable`

- [x] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.

**Proposal:** 
It should use the default value of RollingUpdate if the type is not set.

**Comment by KnVerey** [comment]
👍 I agree
