### ISSUE TITLE
Timing error in watcher's sleep

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#272]
Seen in version 0.18.1, but the lines of code in question hadn't changed for 7 months as of that version, so it's likely this is a rare edge case that has been possible for  a long time.

```
lib/kubernetes-deploy/resource_watcher.rb:23:in `sleep': time interval must be positive (ArgumentError)
  from lib/kubernetes-deploy/resource_watcher.rb:23:in `run'
  from lib/kubernetes-deploy/deploy_task.rb:380:in `deploy_resources'
  from lib/kubernetes-deploy/deploy_task.rb:155:in `run!'
  from exe/kubernetes-deploy:67:in `<top (required)>'

```

**Comment by dturn** [comment]
Code in question is:
`        if Time.now.utc < delay_sync_until
          sleep(delay_sync_until - Time.now.utc)
        end
`

Easy fix ideas are saving the first call to Time.now.utc or `[delay_sync_until, 0.1].max` in the sleep call

**Comment by KnVerey** [comment]
I'm fine with either of those fixes. Interested in making the PR?
