### ISSUE TITLE
New resource watcher test is flakey

### ISSUE THREAD

**Issue by klautcomputing** [Shopify/kubernetes-deploy#274]
### Bug report
We observed that the test `test_resource_watcher_reports_failed_after_timeout` introduced in #73 is very flakey.

**Comment by dturn** [comment]
Bumped `progressDeadlineSeconds` for the deployment we want to hit the global timeout, it was hitting progressDeadlineSeconds deadline about 50% of the time:  https://github.com/Shopify/kubernetes-deploy/pull/273/commits/1817314ccca384ebc3ce7456d31c116713a7f355

Leaving this open for a bit to make sure that was the only flakey part of the test.
