### ISSUE TITLE
Yaml validation not working as intended around kind object

### ISSUE THREAD

**Issue by alexcurtin** [Shopify/kubernetes-deploy#277]
# Bug report

[Description of the bug]

If you try to deploy a .yml kubernetes file but forget to enter in the `kind:` object, e.g. `kind: ConfigMap` OR if you put a space before the ` apiVersion: ` at the top of any kubernetes object `kubernetes-deploy` gem stack traces with:

```
/Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/kubernetes_resource.rb:35:in `const_defined?': no implicit conversion of nil into String (TypeError)
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/kubernetes_resource.rb:35:in `build'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:241:in `block (2 levels) in discover_resources'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:253:in `block in split_templates'
	from /Users/acurtin/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:462:in `block in load_stream'
	from /Users/acurtin/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/psych/handlers/document_stream.rb:19:in `end_document'
	from /Users/acurtin/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse'
	from /Users/acurtin/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /Users/acurtin/.rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/psych.rb:461:in `load_stream'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:252:in `split_templates'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:240:in `block in discover_resources'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:237:in `foreach'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:237:in `discover_resources'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/lib/kubernetes-deploy/deploy_task.rb:125:in `run!'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/gems/kubernetes-deploy-0.19.0/exe/kubernetes-deploy:73:in `<top (required)>'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/bin/kubernetes-deploy:23:in `load'
	from /Users/acurtin/.rvm/gems/ruby-2.3.4/bin/kubernetes-deploy:23:in `<main>'
```

I put a binding here in `kubernetes_resource.rb` and it catches that `definition["kind"]` is nil if you omit it, or if your yaml has a space in the very first line. 

```
class << self
      def build(namespace:, context:, definition:, logger:)
        opts = {namespace: namespace, context: context, definition: definition, logger: logger}
        # binding.pry
        if definition["kind"].nil?
          raise FatalDeploymentError, "Kubernetes object Kind: is missing or yaml is invalid"
        end
        if KubernetesDeploy.const_defined?(definition["kind"])
          klass = KubernetesDeploy.const_get(definition["kind"])
          klass.new(**opts)
        else
          inst = new(**opts)
          inst.type = definition["kind"]
          inst
        end
      end
```

**Expected behavior:** [What you expected to happen]

I would expect the yaml validation to fail or be called earlier, since `kubectl create -f configmap.yaml --dry-run` with a bad configmap.yaml (either missing kind: or space at start of first line) does error out with `error: error converting YAML to JSON: yaml: line 1: did not find expected <document start>`

**Actual behavior:** [What actually happened]

I got the above stack trace since definition["kind"] never got parsed or was missing, its nil.

**Version(s) affected:** [run `kubernetes-deploy --version`]

v0.19.0

### Steps to Reproduce

1. Create a kubernetes resource (configmap, deployment etc) but omit the kind: spec in the file or add an accidental white space at the start of the file.
2. Run the gem against these files against minikube or any version of kubernetes
3. Get stack trace listeed above.

# Feature request

- [ ] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** [provide details on the behaviour you'd like to see and why it would be useful]

Better error handling/rescue if `kind:` is missing or the yaml has a whitespace at the start of the first line.

**Comment by dturn** [comment]
@alexcurtin Thanks for the bug report. The gem shouldn't be crashing. I should have a fix for soon.
