### ISSUE TITLE
Pick a name?

### ISSUE THREAD

**Issue by kirs** [Shopify/kubernetes-deploy#30]
When I extracted the script from shipit-engine, I named the repo as the snippet was named in Shipit. However this isn't a great name for the project because all Shipit snippets are named in a very straightforward manner:

```
$ ls lib/snippets
deploy-to-gke
extract-gem-version
fetch-gem-version
fetch-heroku-version
push-to-heroku
...
```

These are great names for a bash snippet in `bin/`, but not for a individual project.
My point here is that we didn't call it "sysv-resource-limiter", we called it "Semian".
I think this project would benefit from an expressive name.

thoughts? @sirupsen @KnVerey

**Comment by KnVerey** [comment]
I demo'd this to SIG-apps today and someone messaged me afterwards to point out that "Kubernetes" is copyrighted so we probably _have_ to change the name at some point. Let's start thinking about this again. @Shopify/cloudplatform

**Comment by camilo** [comment]
@KnVerey I like this name tho, is pretty descriptive we can probably talk to the k8s people and see what they need to let us keep it?

**Comment by stefanmb** [comment]
What about `k8s-deploy`?

**Comment by KnVerey** [comment]
This trademarks list includes "kubernetes" and not "k8s"... not sure how to check conclusively what is ok though. https://www.linuxfoundation.org/trademark-usage

**Comment by stonith** [comment]
Or `kube-deploy`?

**Comment by benlangfeld** [comment]
@KnVerey @kirs Has a new name been selected? I would be happy to prepare a PR which implements it, potentially together with https://github.com/Shopify/kubernetes-deploy/issues/256, if a name can be chosen.

**Comment by camilo** [comment]
I vote`kates-deploy`

**Comment by dturn** [comment]
@benlangfeld Thanks for the offer! We haven't picked a name yet, is there one you like?

**Comment by KnVerey** [comment]
My favourite name of the ones that have come up over the years is "KAP". It's a reference to the capistrano deployment tool + the word "captain", in keeping with Kubernetes's nautical theme. We can say it stands for "K8s App Provisioner" or something like that. I also like that it offers a short base name for the executable: `kap deploy`, `kap restart` etc.

**Comment by benlangfeld** [comment]
The problem with `kap` is that verbally it's the same as `cap`, which would surely lead to masses of confusion.

**Comment by benlangfeld** [comment]
What about `purser`, the officer in charge of passengers (apps) on a ship?

**Comment by ibawt** [comment]
`yak-deploy` yet another kubernetes deploy

**Comment by KnVerey** [comment]
> What about `crane`, as in the thing which lifts containers on to and off of ships?

That's pretty good! It'd have to be `krane` though, as a `crane` rubygem already exists.

> The problem with `kap` is that verbally it's the same as `cap`, which would surely lead to masses of confusion.

I'm not super worried about this personally.

**Comment by benlangfeld** [comment]
I like `krane` a lot 😁

**Comment by benlangfeld** [comment]
@KnVerey What sort of approval is necessary for the name selection?

**Comment by KnVerey** [comment]
We held a discussion and vote among the current maintainers, and `krane` is the winner! Thanks for the great suggestion @benlangfeld ! 🥇

**Comment by benlangfeld** [comment]
Excellent. Once https://github.com/Shopify/kubernetes-deploy/pull/424 and https://github.com/Shopify/kubernetes-deploy/pull/421 get merged and https://github.com/Shopify/kubernetes-deploy/issues/256#issuecomment-467250443 has an answer I'll prep a PR for that.

**Comment by dturn** [comment]
@benlangfeld Have you started on this work? If you haven't we may add it to our next sprint, but we don't want to duplicate work.

**Comment by benlangfeld** [comment]
I haven’t yet, I apologise. I got pulled off to work on other things. I’m not sure when I might get time to come back to this.

**Comment by dturn** [comment]
No need to apologize! We'll update here once we start working on it.

**Comment by dturn** [comment]
We've picked a name and will tracking the work in #256
