### ISSUE TITLE
kubernetes-run should watch the pod & dump its logs

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#304]
IMO this should actually be the default behaviour, and we should provide a `--skip-wait` flag like `kubernetes-deploy` itself has to override it. The primary user of `kubernetes-run` internally at Shopify is ActiveFailover, which is implementing log tailing itself. Other apps are using it in Shipit tasks, where waiting and seeing logs also strikes me as better behaviour in the average case.

cc @dturn @klautcomputing @fw42

**Comment by dwradcliffe** [comment]
I came across another need for this too, so I'm glad we're in agreement that this should be a feature. 😄
Right now I'm hacking it together by faking a full deploy, but that's really clumsy.

**Comment by fightingtheboss** [comment]
I don't know much about how this works, but happy to contribute if I can help move this effort forward. 

It would make the Database Snapshot Service usable from a Shipit task rather than requiring users to run the rake task on a production web pod.

**Comment by dturn** [comment]
This is in progress. You can follow along in: https://github.com/Shopify/kubernetes-deploy/pull/320
