### ISSUE TITLE
predeployed resources are deployed again during phase 5

### ISSUE THREAD

**Issue by dwradcliffe** [Shopify/kubernetes-deploy#313]
# Bug report

Predeployed resources seem to be deployed again during the main deploy phase (`Phase 5: Deploying all resources`). In theory this is a NOOP, I think, but seems surprising and possibly adds unnecessary work.

**Expected behavior:**
Any resources deployed in phase 4 should be absent from phase 5.

**Actual behavior:**
All resources deployed in phase 4 are also present in phase 5.

I also observed this took 57 seconds when the deploy was only one (predeployed) resource. So this NOOP added a minute to the total time, in this case.

```
[INFO][2018-07-06 17:00:11 -0400]	------------------------------Phase 4: Predeploying priority resources------------------------------
[INFO][2018-07-06 17:00:11 -0400]	Deploying Pod/upload-assets-a26200c8-57303457 (timeout: 600s)
...
[INFO][2018-07-06 17:03:04 -0400]	Successfully deployed in 173.1s: Pod/upload-assets-a26200c8-57303457
[INFO][2018-07-06 17:03:04 -0400]
[INFO][2018-07-06 17:03:04 -0400]	----------------------------------Phase 5: Deploying all resources----------------------------------
[INFO][2018-07-06 17:03:04 -0400]	Deploying Pod/upload-assets-a26200c8-57303457 (timeout: 600s)
[INFO][2018-07-06 17:04:02 -0400]	Successfully deployed in 57.8s: Pod/upload-assets-a26200c8-57303457
```

**Version(s) affected:**
v0.20.3

### Steps to Reproduce

1. Add a Pod resource such as uploading assets.
2. Deploy

**Comment by KnVerey** [comment]
Including them in phase 5 is intentional: if we did not, they would get pruned. What strikes me as really strange though is that the "no-op" took any time. I'd be very interested to know what was going on with the state of that pod in the cluster during phase 5. i.e. if it ran to completion in phase 4, what could phase 5 have been waiting for?

**Comment by dwradcliffe** [comment]
Makes sense. Closing since this is as expected.
We can try to tune things to reduce the time spent in the NOOP in another issue/PR.
