### ISSUE TITLE
Bypass batched fetching for small numbers of resources

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#314]
# Bug report

Reported in https://github.com/Shopify/kubernetes-deploy/issues/313. The root cause there is that the namespace being deployed to has over 4000 pods, most of which are old evicted pods. Since we are unconditionally using the batched fetching strategy, our sync cycles fetch and initialize all 4000+ pods even though in the example given only a single one was needed.

**Expected behavior:** Polling is instant for small resource groups.

**Actual behavior:** Polling can take forever for small resource groups, if the cluster contains a large number of resources of that type.

**Version(s) affected:** Latest.

# Proposed solution

Wrap https://github.com/Shopify/kubernetes-deploy/blob/master/lib/kubernetes-deploy/sync_mediator.rb#L32-L37 in something along the lines of `if resources.length < LARGE_BATCH_THRESHOLD` and add/adjust tests.

cc @dwradcliffe @csfrancis (likely affects overall core deploy speed too) @Shopify/cloudx

**Comment by dturn** [comment]
The PR has been merged. It still need to be released (waiting to ship 2 or 3 more PRS) then bumped in core.
