### ISSUE TITLE
Rollback should skip unmanaged pods

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#33]
Currently, Shipit rollbacks using this gem are identical to a deploy of the previous revision, which means that unmanaged pods will get run. This is likely contrary to expected behaviour (though I have not heard any specific complaints), and it unnecessarily slows down rollbacks while the pod is deployed and runs to completion. Note that our primary use case for unmanaged pods is Rails migrations, in which case this is launching a container with the old revision and running `rake db:migrate` as it would have when that revision was first deployed.

**Comment by KnVerey** [comment]
@Shopify/cloudplatform @kirs any opinions on this one? What do you think is the more correct behaviour?

**Comment by kirs** [comment]
This is true for migrations but may not be true for assets.
Depending on whether you use CDN or not, you may need to recompile them on rollback. At least that's what capistrano-rails does: https://github.com/capistrano/rails/blob/f4befc4edc8b287e2317ccd1150c793fe337eebb/lib/capistrano/tasks/assets.rake#L62

@ibawt I know that with the current assets setup in cloud, the app is responsible to call `rake cloudplatform:upload_assets`. But are those ever expired/garbage collected? What happens with assets from an old revision?

**Comment by ibawt** [comment]
do you mean the pods themselves?  if we do a pod like we do for the other rails apps, there's only 1, it will stick around in completed but shouldn't require any cleanup really.

Assets from an old revision I imagine if un-digested will get overwritten for every deploy depending on the sha, roll back or not.

For now we aren't uploading the assets from cloud, just from the container builder.

**Comment by KnVerey** [comment]
@ibawt it's the assets themselves that we're wondering about, for cloud apps that are using an unmanaged pod to upload them. The question is whether we need to run an asset uploader pod on rollbacks, or whether (like migration pods) running one is inherently a no-op that unnecessarily delays the meat of the rollback.

> Assets from an old revision I imagine if un-digested will get overwritten for every deploy depending on the sha, roll back or not.

So does this mean the answer is that we do need to re-upload on rollback?

**Comment by ibawt** [comment]
yes.  there's "unversioned" assets.

**Comment by ibawt** [comment]
which is a terrible pattern, but here we are

**Comment by KnVerey** [comment]
Ok, this issue is misguided then. Closing.

**Comment by kirs** [comment]
Maybe we could use a special annotation and skip migration pod on rollback?

**Comment by KnVerey** [comment]
Yeah, that would work. If you think that's worth implementing let's open a new issue for it.
