### ISSUE TITLE
Consistent preflight validations for all tasks

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#344]
Follow-up to https://github.com/Shopify/kubernetes-deploy/pull/337

The deploy task already checks whether it can reach the API server before proceeding, so that it can fail with a relevant message instead of failing whichever other request happens to be made first. We should do the same in the runner task. In fact, we should make sure that all globally applicable preflight validations are done consistently by all four of our tasks. One possible approach would be to introduce a config validator object for this purpose, as prototyped here: https://github.com/Shopify/kubernetes-deploy/compare/config_validator.

- Determine all of the appropriate pre-flight validations should be in place across all tasks
- Make sure they are being executed consistently (including order)

Considerations
- Maybe we make a generic validation class that can be reused or something specific for each task

**Comment by dturn** [comment]
https://github.com/Shopify/kubernetes-deploy/pull/533 Added a `TaskConfig` and `TaskConfigValidator` to each task. But it only added the full set of pre-flight validations to the RestartTask. We need to add it to the remaining tasks to close out this issue. 

When working on adding the full set of pre-flight validations to the remaining tasks, consider if we need sub classes like `DeployTaskConfig` and `DeployTaskConfigValidator` (or punt this to a new issue).

**Comment by dturn** [comment]
Done.
