### ISSUE TITLE
Command failure warnings should include the command itself

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#35]

**Comment by kirs** [comment]
As I see both `kubectl` runners log the command:

https://github.com/Shopify/kubernetes-deploy/blob/master/lib/kubernetes-deploy/kubernetes_resource.rb#L120
https://github.com/Shopify/kubernetes-deploy/blob/master/lib/kubernetes-deploy/kubernetes_resource.rb#L120

Maybe I misunderstood and there's more you want to log?

**Comment by KnVerey** [comment]
You're right, I think this has been fixed already with https://github.com/Shopify/kubernetes-deploy/commit/8db202f529c531cadc6384aff0ebff3032c108e0 and  https://github.com/Shopify/kubernetes-deploy/commit/c5a4a585c992dd300f8c75371ec007f1c9ed7071. 😄
