### ISSUE TITLE
HPA setup flakey on k8s-ci clusters

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#373]
This seems relatively common, though it is being hidden by automatic retries (which I'd prefer to disable). This will only get worse now that we have two versions (1.11 and 1.12) using this queue.

Example build where 1.11 fails: https://buildkite.com/shopify/kubernetes-deploy-gem/builds/1098#5d2a9ff0-5181-4816-a7b8-1e4ff6781bac
Example build where 1.12 fails: https://buildkite.com/shopify/kubernetes-deploy-gem/builds/1097#ed4ac1f1-2046-4236-9108-e13689038b3b

@Shopify/cloudx

**Comment by KnVerey** [comment]
We're doing a blind `create` of the metric server resources, so one good thing to check would be whether there's something we could look at to make sure that setup was successful (and retry it).

**Comment by randy-abson** [comment]
Adding this to Kanbanize
