### ISSUE TITLE
[bug] indent_four doesn't protect against nil input

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#378]
# Bug report
 A bad template can cause a crash by passing nil to indent_four

**Expected behavior:**  K8s-deploy to print a message about why the template is invalid

**Actual behavior:**  crash

**Version(s) affected:** This happened on 0.22.0, but likely is much older

cc: @stefanmb 
### Stack trace

```/usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:292:in `indent_four': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:287:in `record_invalid_template'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:442:in `block (2 levels) in record_apply_failure'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:442:in `each'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:442:in `block in record_apply_failure'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:439:in `each_line'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:439:in `record_apply_failure'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:419:in `block in apply_all'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:401:in `apply_all'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:388:in `deploy_resources'
	from /usr/lib/ruby-shopify/ruby-shopify-2.4.3/lib/ruby/gems/2.4.0/gems/kubernetes-deploy-0.22.0/lib/kubernetes-deploy/deploy_task.rb:163:in `run!'```

**Comment by stefanmb** [comment]
So the tricky part is that it's not the template itself that's bad, but rather `kubectl` fails to patch the existing resource, this is what I saw running locally:

> for: "config/deploy/staging/agent.yml.erb": The order in patch list:
[map[name:ENV value:production] map[name:ENV value:staging] map[name:GOOGLE_APPLICATION_CREDENTIALS value:/secrets/gcloud-key] map[name:BUILDKITE_AGENT_TOKEN valueFrom:map[secretKeyRef:map[name:deployer]]]]
 doesn't match $setElementOrder list:

**Comment by KnVerey** [comment]
In case it matters, which Kubernetes client/server versions did we see this with?

**Comment by stefanmb** [comment]
`kubectl` was v1.10.4 on Shipit and v1.10.7 locally on my machine. The cluster was deleted and I'm not sure where in the logs to find the server version retroactively.

**Comment by KnVerey** [comment]
I fixed this when I centralized `indent_four` onto `FormattedLogger`.
