### ISSUE TITLE
Support label-based sub-namespace resource management

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#411]
i.e. revive and merge https://github.com/Shopify/kubernetes-deploy/pull/235

**Comment by benlangfeld** [comment]
What remains to be done on #235 to get it merged? A skim of the review comments suggests they were all either addressed or withdrawn.

**Comment by KnVerey** [comment]
IIRC there was an unresolved gotcha related to selector-based pruning of secrets derived from EJSON.  At this point, the PR is a year old and will need a major rebase. But you're right that it was very close to the finish line.
