### ISSUE TITLE
Deploying ejson only fails

### ISSUE THREAD

**Issue by RappC** [Shopify/kubernetes-deploy#412]
# Bug report

kubernetes-deploy always expects at least a valid yml|yml.erb file within the template directory, although a valid `secrets.ejson` file exists and could be applied to the cluster.

**Expected behavior:** 
Secret created successfully in targeted namespace.

**Actual behavior:** 
`kubernetes-deploy` failes the deploy with the message: `<given-template-dir> doesn't contain valid templates (postfix .yml or .yml.erb)`

**Version(s) affected:**
0.23.0

### Steps to Reproduce
run `kubernetes-deploy` in a template directory where there is only a `secrets.ejson` file for a namespace which exists.

As soon as a valid yaml is placed file into the template directory besides `secret.ejson` the ejson file is decrypted and being applied correctly along side the other yaml file(s).

**Comment by RappC** [comment]
Adding an empty yaml file besides the `secrets.ejson` works around this issue. The empty file is ignored when applying kubernetes manifests.

**Comment by KnVerey** [comment]
Thanks for the bug report! I agree that it should work to deploy `secrets.ejson` on its own.
