### ISSUE TITLE
Need to support a "restart" button in Shipit

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#43]
Right now, app maintainers need to push a new commit, triggering a new container build, to "restart" their application. We need a true restart mechanism, ideally enabling users to choose to restart only a specific deployment rather than all of them if desired.

Note that there has been some [discussion](https://github.com/kubernetes/kubernetes/issues/13488) re: adding a feature like this to kubectl. It's still open, but my read on the tl;dr there is that the maintainers are conceptually opposed to implementing it, since restarts should not be necessary when no changes have been made to the spec and both liveness and readiness probes are passing. 

As that k8s issue points out, rather than implementing selective pod deletion in accordance with the deployments rollout strategy, this can be achieved by patching the deployment's podspec, e.g. with an environment variable, a label or an annotation containing a timestamp.

**Comment by kirs** [comment]
Initially I was thinking about the selective pod deletion (kind of `kubectl get pod | grep 'pod-name' | cut -d " " -f1 - | xargs -n1 -P 10 kubectl delete pod`), but you're right that we'd need to reimplement the rollout strategy. Patching the deployment spec with an annotation or label or env variable sounds more feasible here.

I also think it should be a separate command. It should accept the deployments we want to restart (web + jobs in our case) and the namespace + context:

`kubernetes-restart --context cloud1 --namespace trashbin --deployment jobs,web`

WDYT?

cc @ibawt

**Comment by KnVerey** [comment]
> I also think it should be a separate command. It should accept the deployments we want to restart (web + jobs in our case) and the namespace + context:
> 
> kubernetes-restart --context cloud1 --namespace trashbin --deployment jobs,web

Sounds right to me. I would also like us to make the necessary changes on the shipit side so that any app using the first-class `kubernetes: ` syntax automatically gets a button for this task, with the ability to set the targeted deployments via env vars.

**Comment by kirs** [comment]
I've done experiments and checked whether updating labels or annotations of a deployment triggers the restart.

```
EPOCH=$(date +%s)
kubectl patch deployment web -n trashbin \
  -p '{"metadata":{"labels":{"restarted_at":"'$EPOCH'"}}}'
```

This results to the deployment labels updated but no restart, which makes sense because only the metadata is changed.

```
RESTART_DATE=$(date -u '+%Y-%m-%dT%H:%M:%S%z')
kubectl patch deployment web -n trashbin \
  -p '{"metadata":{"annotations":{"restarted_at":"'$RESTART_DATE'"}}}'
```

Same thing: the annotations are updated but no restart. It also makes sense since it's only metadata change.

```
RESTART_DATE=$(date -u '+%Y-%m-%dT%H:%M:%S%z')
kubectl patch deployment web -n trashbin \
  -p '{"spec":{"template":{"spec":{"containers":[{"name":"app","env":[{"name":"RESTARTED_AT","value":"'$RESTART_DATE'"}]}]}}}}'
```

Updating the env variables triggers the restart that follows the rollout strategy.

**Meaning that so far updating the ENV variable with a timestamp is the only way to kick off the restart.**
