### ISSUE TITLE
Support Shipit visualization

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#45]
This feature will mostly be on the shipit-engine side, but will require some work in this gem. The primary purpose of the `KUBESTATUS` logs is to support such a visualization. Some thoughts:
* Ideally these logs would be hidden from the deploy output if possible (though it probably isn't) to make the deploy output itself more human-friendly than it typically is today.  
* Having the visualization help educate app maintainers about what actually happens during kubernetes deploys should be a goal. For example:
  * make surge/unavailability visible
  * don't make it look like pods restart rather than are replaced
* If we stay with representing the entities being rolled out with coloured boxes, perhaps we could add a hover state revealing more info about that entity, e.g. the name and status string, and the logs if it is a pod and has failed.

**Comment by KnVerey** [comment]
I don't think we're planning to do this at all anymore. We dramatically improved the logged output instead. @kirs reopen if you disagree.

**Comment by kirs** [comment]
I'd really like to see kubernetes-deploy support rollout visualization that we already have for borg in Shipit. I agree that could be time consuming and the state of rollout is already pretty good with the improved logging.
