### ISSUE TITLE
Investigate public CI

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#452]
**Problem:**
 
External contributors can not interact with our CI system, beyond ✅  / ❌  and even that requires a Shopify employee to kick off the run. This sucks for everyone. Employees have to remember to run the test suite and external contributors have to wait till an employee provides them with failing test status. 

**Proposal:** 

Investigate adding a public CI component. I believe circleci or travis is free to open source projects. We also should consider if this is enough to remove Shopify CI or if we want to run both. If we have to keep internal CI the external CI will need to be easy to maintain, (this isn't trivial)

_note:_ Please do not sink more than an hour or so into this task with reporting back. This might be a yak shave or worse.

**Comment by rendhalver** [comment]
Circle-CI might be a good option for this.
[helm/charts](https://github.com/helm/charts) uses Circle-CI for testing and it works pretty well.
Travis-CI also works well.
Given this is an open source project there would also be no cost for either option.
I would also be happy to volunteer some time to help getting this setup.

**Comment by dturn** [comment]
Thanks for offering to look into this and sorry for the slow response. We've got some internal discussion going on and think we have a simpler solution than building a new external pipeline. I'll update here once we have some concrete progress.

**Comment by dturn** [comment]
Closing for now, will revaluate if the amount of external contributions grows.
