### ISSUE TITLE
ScaleTask for scaling deployments to a particular replica count

### ISSUE THREAD

**Issue by benlangfeld** [Shopify/kubernetes-deploy#459]
# Feature request

If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.

**Proposal:** A `scale` task, similar to `RestartTask` which patches `Deployment/spec/replicas`.

Our use case is replacing the schema of a SQL database used by an application deployed by `kubernetes-deploy`. While this schema reload is happening, we want to effectively shut down application processes to prevent them from encountering and loudly reporting errors. Our plan is to scale all Deployment resources to a replica count of 0, reload the database schema, and then trigger a deployment.

An alternative approach would be to perform a new deployment with the replica-count set to 0, but this requires adding logic to templates to prevent running bare pods for the likes of database migrations in the initial deployment.

**Comment by KnVerey** [comment]
Do I understand correctly that the value added over using `kubectl scale` is that it would affect multiple `Deployment` resources identified via an annotation?

Might something like `kubectl scale --replicas=0 deployment --all --selector=scale-me=true` work for your use case?

**Comment by benlangfeld** [comment]
@KnVerey Such a command prints "error: no objects passed to scale". I ended up using this:

```bash
kubectl get deployments --no-headers=true --output=name --selector=foo | xargs -I % kubectl scale --replicas=0 %
```

**Comment by KnVerey** [comment]
That error sounds like maybe the selector was wrong of one of the args was missing? It works fine for me:

![image](https://user-images.githubusercontent.com/4789493/55501210-ebb11b80-5617-11e9-98da-a6cfcfa25268.png)

**Comment by benlangfeld** [comment]
Indeed you're right. I'm not sure what I had been doing last time I tried, but your example does work. Apologies for the noise. I don't think this does carry enough value to move forward.

**Comment by Ticiano-mw** [comment]
I was having the same problem. It was the halloweed namespace selection! You probably were missing the
 `-n <namespace>` flag to your scale command like me.
Cheers!
