### ISSUE TITLE
Support more resource types

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#46]
We only selected a few that our own apps commonly use for the initial rollout. Currently unrecognized types will be kubectl applied and a warning will be logged about the fact that the script does not know how to check whether they actually came up.

**Comment by KnVerey** [comment]
I've now seen StatefulSet and Secret 😱  in use by our apps (the latter for a case that should be using a configmap).

**Comment by wfarr** [comment]
Maybe a default fallback handler that does a fire-and-forget `kubectl apply`? Most of these resource types probably don't need custom blocking behavior.

**Comment by KnVerey** [comment]
> Maybe a default fallback handler that does a fire-and-forget kubectl apply?

That's exactly what already happens (and it logs a warning that it did so). 😄

**Comment by karanthukral** [comment]
Daemon Sets also use `ownerReferences` and `revision` to match with pods. We should be able to replicate the logic currently used by deployments currently

**Comment by dturn** [comment]
HPA support has been merged https://github.com/Shopify/kubernetes-deploy/pull/305.

**Comment by KnVerey** [comment]
With HPA in, I think we can actually close this. I don't see any unsupported resources left that actually report a status, i.e. where supporting them explicitly would actually improve deploy behaviour. For example, there are a bunch of policy objects (LimitRange, PodSecurityPolicy, Role, RoleBinding...) we don't model, but they're typically controller-managed, and we could trivially add them on-demand if others say they do want to use kubernetes-deploy to manage them. Adding resources like those effectively just suppresses the warning.
