### ISSUE TITLE
Can CRs be sensitive?

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#475]
# Feature request

**Proposal:** Support a new CRD annotation that would let cluster administrators inform us that a CR's content is sensitive. We'd then treat such CRs the same way as secrets. See https://github.com/Shopify/kubernetes-deploy#deploying-custom-resources for the annotations we currently support.

Shopify doesn't have a use case for this at this time, but if we hear there's a need for it, it should be easy enough to implement.

**Comment by dturn** [comment]
Stale. If anyone is interested please re-open.
