### ISSUE TITLE
Argument parsing in scripts is too permissive

### ISSUE THREAD

**Issue by DazWorrall** [Shopify/kubernetes-deploy#482]
## Bug report

* When required arguments are missing (e.g. context and namespace) the fail state is inconsistent:

```
$ kubernetes-restart 
[INFO][2019-05-15 10:05:00 +0100]
[INFO][2019-05-15 10:05:00 +0100]       -----------------------------------Phase 1: Initializing restart------------------------------------
[INFO][2019-05-15 10:05:00 +0100]
[INFO][2019-05-15 10:05:00 +0100]       ------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2019-05-15 10:05:00 +0100]      `` context must be configured in your kubeconfig file(s) (/users/daz/.kube/config).
[FATAL][2019-05-15 10:05:00 +0100]
```

vs 

```
$ kubernetes-deploy
[ERROR][2019-05-15 10:07:16 +0100]      Template directory is unknown. Either specify --template-dir argument or set $ENVIRONMENT to use config/deploy/$ENVIRONMENT as a default path.
```

* Script execution continues even when invalid options are passed

```
$ kubernetes-deploy --foo
kubernetes-deploy: invalid option: --foo
[ERROR][2019-05-15 10:07:59 +0100]      Template directory is unknown. Either specify --template-dir argument or set $ENVIRONMENT to use config/deploy/$ENVIRONMENT as a default path.
```

(This one is due to our use of [`#options`](https://github.com/ruby/ruby/blob/c9b28fd7ae5c5a79a74afebd5b191cfd2f31a65f/lib/optparse.rb#L2126-L2129) without checking the result of the block)

**Expected behavior:** 

* Error messaging for common fail states between the CLI tools (e.g. missing required arguments) is clear and consistent - this bug report originates from a user who was unable to get `kubernetes-run` to work as they expected
* Passing invalid options aborts execution

**Version(s) affected:** Examples from v0.26.4

**Comment by dturn** [comment]
I think this will be good to keep in mind as we transition to the new `krane` cli, but seems low priority for now.

**Comment by KnVerey** [comment]
I've added proper required arg handling as a requirement for our new CLI: https://github.com/Shopify/kubernetes-deploy/issues/256. https://github.com/Shopify/kubernetes-deploy/issues/344 will also provide relevant UX improvements. I'm going to close this issue because I think those two others already reflect the actual work required to resolve this bug.
