### ISSUE TITLE
Error decrypting secret.ejson

### ISSUE THREAD

**Issue by strowi** [Shopify/kubernetes-deploy#492]
# Bug report

[Description of the bug]
deploying with a secret.json fails.

**Expected behavior:** [What you expected to happen]
manifests + secret deployed to k8s.

**Actual behavior:** [What actually happened]
deployment fails with:
```
[INFO][2019-05-30 19:03:53 +0200]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2019-05-30 19:03:53 +0200]	Context test1 found
[INFO][2019-05-30 19:03:54 +0200]	Namespace testns found
[INFO][2019-05-30 19:03:55 +0200]	All required parameters and files are present
[INFO][2019-05-30 19:03:55 +0200]	Discovering templates:
[INFO][2019-05-30 19:03:55 +0200]	
[INFO][2019-05-30 19:03:55 +0200]	------------------------------------------Result: FAILURE-------------------------------------------
[FATAL][2019-05-30 19:03:55 +0200]	Generation of kubernetes secrets from ejson failed: decryption failed: encoding/hex: invalid byte: u+004d 'm'

[FATAL][2019-05-30 19:03:55 +0200]	
```
manually decrypting the ejson works.

**Version(s) affected:** [run `kubernetes-deploy --version`]
at least v0.26,4 on ubuntu-18.04 and alpine:3.8/3.9:

### Steps to Reproduce

1. create secret.json:
```

{
  "_public_key": "masked",
  "kubernetes_secrets": {
    "amppackager-secret": {
      "_type": "Opaque",
      "data": {
        "www.privkey": "masked",
        "www.cert": "masked"
      }
    }
  }
}

```
2. run `ejson encrypt secret.json`
3. REVISION="manual"  kubernetes-deploy testns test1 --template-dir=./template

regards,
strowi

**Comment by dturn** [comment]
Thanks for the bug report. I tried to reproduce the issue you hit, but it looks like the actual cypher text is relevant. Any chance you can give me a fake value that triggers this?

its also possible the issue is in the json code `decryption failed: encoding/hex: invalid byte: u+004d 'm'` is most likely directly from ejson https://github.com/Shopify/kubernetes-deploy/blob/master/lib/kubernetes-deploy/ejson_secret_provisioner.rb#L148

**Comment by strowi** [comment]
thx for getting back so quickly! 
I'm puzzled, because this happens with whatever value i put into the secrets.json:
```
{
  "_public_key": "ab58d08857174304a995a5d68f272b7c317024764e38185cf9cb71f6e7125e32",
  "kubernetes_secrets": {
    "s3access2": {
      "_type": "Opaque",
      "data": {
        "accesskey": "EJ[1:COnDrbefV+moh5AfmE+SeBIuKzx5NY2kuKeaghBwWWw=:I2gfy61h+yWM3PBxb/HHbQFv8uRfG9Oy:hJ2Z5GqwgWhHxOcziDcDxny7PbFOx4A=]",
        "secretkey": "EJ[1:COnDrbefV+moh5AfmE+SeBIuKzx5NY2kuKeaghBwWWw=:JiA7/QQFDppJz0Xn+rbfhCHSBo2Z+m66:os1WOw0SE6jxFUpikuU8XiaHPQ==]"}
    }
  }
}
```
using ejson directly works..
```
~> ejson  --keydir=./keys d manifests/secrets.ejson                                                                                                                        (ci-support/rook-ceph)
{
  "_public_key": "ab58d08857174304a995a5d68f272b7c317024764e38185cf9cb71f6e7125e32",
  "kubernetes_secrets": {
    "s3access2": {
      "_type": "Opaque",
      "data": {
        "accesskey": "testing",
        "secretkey": "123"}
    }
  }
}
```

**Comment by strowi** [comment]
aegh.. so sorry... turns out there was an error in the ejson-keys secret, don't know how it got introduced in only a single ns... Testing on minikube got me into the right direction.
But maybe the error-message could be improved?

**Comment by dturn** [comment]
Glad you got it figured out!

**Comment by binoytechjini** [comment]
Hi @strowi ,

Getting the same error. Can you help out with how you solved the issue or any steps ?

**Comment by strowi** [comment]
@binoytechjini well as I wrote before, it was an error with the content of the secret. So i tried replicating it locally with the same values and checked trends result..
