### ISSUE TITLE
kubernetes-deploy pruned all other resources 

### ISSUE THREAD

**Issue by shashankkoppar** [Shopify/kubernetes-deploy#515]
Bug report: kubernetes-deploy pruned all other resourvces 

[Description of the bug]

**Expected behavior:** [What you expected to happen]
[INFO][2019-07-24 12:37:23 +0000]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2019-07-24 12:37:23 +0000]	Context xxxxxxx found
[INFO][2019-07-24 12:37:23 +0000]	Namespace staging found
[INFO][2019-07-24 12:37:24 +0000]	All required parameters and files are present
[INFO][2019-07-24 12:37:24 +0000]	Discovering templates:
[INFO][2019-07-24 12:37:24 +0000]	  - VirtualService/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - DestinationRule/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - Service/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - Deployment/xxxx-staging
[INFO][2019-07-24 12:37:25 +0000]	
[INFO][2019-07-24 12:37:25 +0000]	----------------------------Phase 2: Checking initial resource statuses-----------------------------
[INFO][2019-07-24 12:37:26 +0000]	Deployment/xxx-staging                            2 replicas, 2 updatedReplicas, 2 availableReplicas
[INFO][2019-07-24 12:37:26 +0000]	DestinationRule/xxx-staging                       Exists
[INFO][2019-07-24 12:37:26 +0000]	Service/xxxx-staging                               Selects at least 1 pod
[INFO][2019-07-24 12:37:26 +0000]	VirtualService/xxxx-staging                        Exists
[INFO][2019-07-24 12:37:26 +0000]	
[INFO][2019-07-24 12:37:26 +0000]	------------------------------Phase 3: Predeploying priority resources------------------------------
[INFO][2019-07-24 12:37:26 +0000]	Deploying DestinationRule/xxxx-staging (timeout: 300s)
[WARN][2019-07-24 12:37:27 +0000]	Don't know how to monitor resources of type DestinationRule. Assuming DestinationRule/xxxx-staging deployed successfully.
[INFO][2019-07-24 12:37:27 +0000]	Successfully deployed in 0.7s: DestinationRule/xxxx-staging
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	Deploying VirtualService/xxxx-staging (timeout: 300s)
[WARN][2019-07-24 12:37:27 +0000]	Don't know how to monitor resources of type VirtualService. Assuming VirtualService/sky-staging deployed successfully.
[INFO][2019-07-24 12:37:27 +0000]	Successfully deployed in 0.7s: VirtualService/xxx-staging
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	----------------------------------Phase 4: Deploying all resources----------------------------------
[INFO][2019-07-24 12:37:27 +0000]	Deploying resources:
[INFO][2019-07-24 12:37:27 +0000]	- Deployment/xxx-staging (progress deadline: 2147483647s)
[INFO][2019-07-24 12:37:27 +0000]	- DestinationRule/xxx-staging (timeout: 300s)
[INFO][2019-07-24 12:37:27 +0000]	- Service/xxx-staging (timeout: 420s)
[INFO][2019-07-24 12:37:27 +0000]	- VirtualService/xxx-staging (timeout: 300s)

[INFO][2019-07-24 12:37:44 +0000]	Successful resources
[INFO][2019-07-24 12:37:44 +0000]	Deployment/xxxx-staging                            2 replicas, 2 updatedReplicas, 2 availableReplicas
[INFO][2019-07-24 12:37:44 +0000]	DestinationRule/xxxx-staging                       Exists
[INFO][2019-07-24 12:37:44 +0000]	Service/xxxx-staging                               Selects at least 1 pod
[INFO][2019-07-24 12:37:44 +0000]	VirtualService/xxx-staging                        Exists

**Actual behavior:** [What actually happened]

[INFO][2019-07-24 12:37:23 +0000]	------------------------------------Phase 1: Initializing deploy------------------------------------
[INFO][2019-07-24 12:37:23 +0000]	Context xxxxxxx found
[INFO][2019-07-24 12:37:23 +0000]	Namespace staging found
[INFO][2019-07-24 12:37:24 +0000]	All required parameters and files are present
[INFO][2019-07-24 12:37:24 +0000]	Discovering templates:
[INFO][2019-07-24 12:37:24 +0000]	  - VirtualService/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - DestinationRule/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - Service/xxx-staging
[INFO][2019-07-24 12:37:24 +0000]	  - Deployment/xxxx-staging
[INFO][2019-07-24 12:37:25 +0000]	
[INFO][2019-07-24 12:37:25 +0000]	----------------------------Phase 2: Checking initial resource statuses-----------------------------
[INFO][2019-07-24 12:37:26 +0000]	Deployment/xxx-staging                            2 replicas, 2 updatedReplicas, 2 availableReplicas
[INFO][2019-07-24 12:37:26 +0000]	DestinationRule/xxx-staging                       Exists
[INFO][2019-07-24 12:37:26 +0000]	Service/xxxx-staging                               Selects at least 1 pod
[INFO][2019-07-24 12:37:26 +0000]	VirtualService/xxxx-staging                        Exists
[INFO][2019-07-24 12:37:26 +0000]	
[INFO][2019-07-24 12:37:26 +0000]	------------------------------Phase 3: Predeploying priority resources------------------------------
[INFO][2019-07-24 12:37:26 +0000]	Deploying DestinationRule/xxxx-staging (timeout: 300s)
[WARN][2019-07-24 12:37:27 +0000]	Don't know how to monitor resources of type DestinationRule. Assuming DestinationRule/xxxx-staging deployed successfully.
[INFO][2019-07-24 12:37:27 +0000]	Successfully deployed in 0.7s: DestinationRule/xxxx-staging
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	Deploying VirtualService/xxxx-staging (timeout: 300s)
[WARN][2019-07-24 12:37:27 +0000]	Don't know how to monitor resources of type VirtualService. Assuming VirtualService/sky-staging deployed successfully.
[INFO][2019-07-24 12:37:27 +0000]	Successfully deployed in 0.7s: VirtualService/xxx-staging
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	
[INFO][2019-07-24 12:37:27 +0000]	----------------------------------Phase 4: Deploying all resources----------------------------------
[INFO][2019-07-24 12:37:27 +0000]	Deploying resources:
[INFO][2019-07-24 12:37:27 +0000]	- Deployment/xxx-staging (progress deadline: 2147483647s)
[INFO][2019-07-24 12:37:27 +0000]	- DestinationRule/xxx-staging (timeout: 300s)
[INFO][2019-07-24 12:37:27 +0000]	- Service/xxx-staging (timeout: 420s)
[INFO][2019-07-24 12:37:27 +0000]	- VirtualService/xxx-staging (timeout: 300s)

[INFO][2019-07-24 12:37:40 +0000]	The following resources were pruned: configmap/test-admin-api-v5-config, configmap/test-test4-config, configmap/test2-admin-api-staging, configmap/test2-billing-cancellation-staging, configmap/test2-billing-validation-staging, configmap/test2-test7-api-staging, configmap/test2-test4-api-staging, configmap/test2-reporting-api-staging, configmap/test2-test6-api-staging, service/ab-api, service/admin-api, service/admin-api-v5, service/test3-api, service/test-admin-api-v5, service/test-admin-ui, service/billing-cancellation, service/billing-validation, service/demo, service/test7-api, service/mock-api, service/test4-api, service/pmt-website, service/reporting-api, service/x1, service/test4as-api, secret/acme-account, secret/admin-api, secret/billing-cancellation, secret/billing-validation, secret/test7-api, secret/test4-api, secret/test0-test111, secret/wildcard-prod, secret/wildcard-staging, secret/wildcard-test, secret/test6-api, deployment.extensions/ab-api, deployment.extensions/admin-api, deployment.extensions/test3-api, deployment.extensions/test-admin-api-v5, deployment.extensions/test-admin-ui, deployment.extensions/billing-cancellation, deployment.extensions/billing-validation, deployment.extensions/demo, deployment.extensions/test7-api, deployment.extensions/mock-api, deployment.extensions/test4-api, deployment.extensions/pmt-website, deployment.extensions/reporting-api, deployment.extensions/salesforce-updater, deployment.extensions/x1, deployment.extensions/test6-api, ingress.extensions/gce-ingress, horizontalpodautoscaler.autoscaling/test4-api, horizontalpodautoscaler.autoscaling/reporting-api, horizontalpodautoscaler.autoscaling/test6-api

[INFO][2019-07-24 12:37:44 +0000]	------------------------------------------Result: SUCCESS-------------------------------------------
[INFO][2019-07-24 12:37:44 +0000]	Pruned 56 resources and successfully deployed 4 resources
[INFO][2019-07-24 12:37:44 +0000]	
[INFO][2019-07-24 12:37:44 +0000]	Successful resources
[INFO][2019-07-24 12:37:44 +0000]	Deployment/sky-staging                            2 replicas, 2 updatedReplicas, 2 availableReplicas
[INFO][2019-07-24 12:37:44 +0000]	DestinationRule/sky-staging                       Exists
[INFO][2019-07-24 12:37:44 +0000]	Service/sky-staging                               Selects at least 1 pod
[INFO][2019-07-24 12:37:44 +0000]	VirtualService/sky-staging                        Exists

**Version(s) affected:** [run `kubernetes-deploy --version`]
v0.26.5

Please fix this bug, within seconds , all our environment was gone and no way to rollback as well!!

**Comment by shashankkoppar** [comment]
It was here 
https://github.com/Shopify/kubernetes-deploy/blob/b37982f1e284cbbbe403451a00ff02f15e6363d4/lib/kubernetes-deploy/kubernetes_resource/custom_resource_definition.rb#L56 
this prunable is hardocded as true and not checked 
https://github.com/Shopify/kubernetes-deploy/pull/516/files

**Comment by dturn** [comment]
Hi @shashankkoppar 

I'm glad you found our tool! I'm really sorry about what happened. I believe there was a  misunderstanding of how pruning works. Kubernetes-deploy is designed to deploy all of the resources to a namespace every time. If a resource is not present in the template directory it assumes you want it deleted. It appears that's not the behavior you'd like, in that case you'll need to use the `--no-prune` flag.

The line of code you found is to allow Custom Resource pruning by opt-in only. Changing it would actually make your case worse, because it would make CR pruning opt-out not opt-in.

**Comment by shashankkoppar** [comment]
oh i see , but previously it used to work and never prune 
i thought it happened because of that

**Comment by shashankkoppar** [comment]
hmm i got it 
then no prune is safer 
i will try it with that option then! 
may be please explicitly mention that it will delete all other resources if not present in directory as Note 
i didnt see it anywhere in readme

**Comment by dturn** [comment]
I think improving the readme is a good idea. Would you be willing to PR a suggested change? As a fresh set of eyes I suspect you'll have a better idea of where to make the edit than I will.
