### ISSUE TITLE
Use --kubeconfig instead of env var in kubectl invocations

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#52]
Make `Kubectl`'s commands use `--kubeconfig` instead of relying on the env var. This will enable us to stop modifying the env var in tests. We should still derive the value of the flag from the environment, as is standard in other tools, so this change will be transparent to end users.

**Comment by rendhalver** [comment]
Why don't we follow the conventions used by kubectl itself?
If you pass --kubeconfig it will ignore the `KUBECONFIG` env var.
Or is that what you are proposing?
This will keep the current behaviour (which is useful in some cases) and extend it.

**Comment by KnVerey** [comment]
This issue is actually about an internal detail of our `KubernetesDeploy::Kubeclient` class, not the CLI args for our commands.

**Comment by dturn** [comment]
Hi @rendhalver. I believe @KnVerey is suggesting: 

>If you pass --kubeconfig it will ignore the `KUBECONFIG` env var.
