### ISSUE TITLE
Rename code references of `kubernetes-deploy` to `krane`

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#527]
## Problem

We're transitioning from kubernetes-deploy to krane. This means we need to remove all references to `kubernetes-deploy` in the code base. 

This issue excludes annotations which are handled in #526 .
This issue excludes the gemspec which is handled in #528 .

## Possible solution
- Update the docs
- Update classes & modules

## Alternative solutions

Split the documentation updates into its own PR. 

## Acceptance criteria
- Results from _greping_  'kubernetes-deploy' returns only annotations, historical change log entries, and the gemspec, shipit.yml. 

## Additional context
https://github.com/Shopify/kubernetes-deploy/issues/256#issuecomment-475580770

**Comment by KnVerey** [comment]
Note: whoever pointed out the other day that our entrypoint methods still don't all have the same name was correct. `RestartTask`'s methods need to be renamed to `run`/`run!` as part of the Krane rename. Before we do the actual release, we should also audit the arguments to make sure they're sensible and consistent (same names for same thing, required vs. optional, on initialize vs on run).

**Comment by dturn** [comment]
>Note: whoever pointed out the other day that our entrypoint methods still don't all have the same name was correct. RestartTask's methods need to be renamed to run/run! as part of the Krane rename. 

Tracking the interface rename in https://github.com/Shopify/kubernetes-deploy/issues/530

>Before we do the actual release, we should also audit the arguments to make sure they're sensible and consistent (same names for same thing, required vs. optional, on initialize vs on run).

Tracking the audit in https://github.com/Shopify/kubernetes-deploy/issues/528. But ideally any work that needs to be done to bring our public interfaces into compliance will be done with the issue that adds the new task.
