### ISSUE TITLE
Use kubeclient gem in place of kubectl in polling code

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#53]
We should be sure to investigate https://github.com/Shopify/kubernetes-deploy/issues/51 before doing this.

**Comment by KnVerey** [comment]
This is high-effort and would add complexity to our code base (we'd have to deal with group version discovery, which kubectl is doing for us today), so we should validate that there's enough expected reward before undertaking it. We do know that `kubectl get` (<= 1.12 anyway) is strangely slow for very large batches of resources, likely related to https://github.com/kubernetes/kubernetes/issues/69856 (as of today, the fix is up but not merged). However, we haven't had reports of other issues with kubectl, and I would not be surprised to encounter problems/gotchas using kubeclient (a much less popular tool) at scale.

**Comment by dturn** [comment]
Revist when `apply` is server side so we can actually remove the dependency on kubectl.
