### ISSUE TITLE
Krane run

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#531]
## Problem

Add the `krane run` command, https://docs.google.com/document/d/1oInUsKplYGNWTymPY48xtDCx3x4Cwc-phcEKUkt2v4U/view# has details on flags that need to be supported.

Ensure that `new` & `run` use the same conventions as the other tasks, if there is a mismatch that needs to be fixed it can be done in a second PR.

This is blocked by #524.

## Possible solution
Build a thor task that calls `RunnerTask.new`. See #530 for thoughts about `--verify-result=false`. 

## Acceptance criteria
- The command must work with all flags
- The command should have tests.

## Additional context

#256 is the tracking issue for the new CLI.

**Comment by RyanBrushett** [comment]
I'll cut an issue for `-f` and try to get time to hack on it myself.
