### ISSUE TITLE
Ruby >=2.4.4 required

### ISSUE THREAD

**Issue by basert** [Shopify/kubernetes-deploy#534]
# Bug report

Installing the gem on ruby < 2.4.x errors due to zeitwerk requiring ruby 2.4.4. zeitwerk is a transitive dependency of https://rubygems.org/gems/activesupport which recently got updated to version 6.x. The version of the dependency should be locked.

**Expected behavior:** Installing on ruby < 2.4.x should be possible

**Actual behavior:** Installation fails

### Steps to Reproduce

1. Use ruby < 2.4.x
2. run `gem install kubernetes-deploy`

**Comment by dturn** [comment]
As part of the 1.0 release we are officially not supporting ruby 2.3
