### ISSUE TITLE
Improve toleration of daemonsets during autoscaling operations

### ISSUE THREAD

**Issue by dalehamel** [Shopify/kubernetes-deploy#565]
# Feature request

- [X] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** 

The current behavior of kubernetes-deploy is flakey when deploying daemonsets to clusters which autoscale. As nodes may be added during the deploy operation, they have little hope of succeeding within the typical timeout window.

The workaround proposed is that we consider only the set of nodes in the target cluster at the beginning of the deploy operation when we make the determining of success, failure, or timeout.

This way, we may filter the daemonset pods which we check against to only those whose node is within this initial list.

My theory is that this will allow for kubernetes-deploy to have a fair chance of succeeding, as the "goal post isn't moving" midway through. If there are flakey nodes, they should still cause a deploy failure on a subsequent deploy.

**Comment by KnVerey** [comment]
Makes sense to me 👍

**Comment by dturn** [comment]
I'm 👍 on this improvement. Though I'm wondering if there is a corresponding problem when nodes are being removed when autoscaling down that needs to be considered? Its fine to submit a PR for just what you wrote and we can consider the downscaling case at a later time.

**Comment by dalehamel** [comment]
Yeah i agree, i'm not actually totally sure downscaling is actually an issue, but if it is we can probably just correspondingly ignore nodes that are explicitly not schedulable

**Comment by dwradcliffe** [comment]
Seems marginally better so I 👍 but probably not enough to make a big difference IMO.

**Comment by dalehamel** [comment]
I think also when scanning the list of nodes, any nodes that are `NotReady` should not be considered for convergence - only ready nodes should be considered. A lot of nodes that stay in the NotReady state may either be booting up or being drained to be shut down.

**Comment by KnVerey** [comment]
@dalehamel can we close this?

**Comment by dalehamel** [comment]
yeah, might want to open a separate issue for another daemonset toleration annotation, but the scope of this one is sufficiently covered by #580 i think.
