### ISSUE TITLE
Krane run -f

### ISSUE THREAD

**Issue by RyanBrushett** [Shopify/kubernetes-deploy#568]
# Problem 

Command is there but `-f` flag as explained in https://docs.google.com/document/d/1oInUsKplYGNWTymPY48xtDCx3x4Cwc-phcEKUkt2v4U/view# was not added yet.

# Possible solution

- Add the flag. 
    - I imagine it co-existing with the `--template` option and having one or the other be required, though that is not what the document says. Happy to chat about this but I don't think we should remove `--template`.
- Should be repeatable and be able to point to multiple files.

# Alternative solutions

Don't add the flag but I think we're pretty determined that it should be an option for `run`.

**Comment by KnVerey** [comment]
You're right, the current `--template` flag lets you specify a template that is already live in the target namespace _by name_, which is super handy and not what `-f` will cover. I agree that we should keep it, but maybe we can improve the name? I probably had a hand in it, and _I_ find it unclear what the value of the flag should be. `--fetch-pod-template / -t`? Also its default value is kinda random (`task-runner-template`); should we remove it or change it to something like `krane-run-template`?

A few other complications come to mind now that I come back to thinking about this:
- We wanted to have `-f` for consistency, but does it really make sense? Maybe we didn't really think it through enough. If you have the template locally, why would you write a pod template and expand it with our util instead just writing a deployable pod spec yourself? 
- If we have both flags, are they mutually exclusive? Both repeatable? This could get confusing, especially if either has a default.
- Would it really be possible to make it repeatable? That for sure would get hairy in combination with any of the args/env-modifying flags.

My inclination (not a strong opinion at this time) is to improve the current flag's name, remove its default, and not provide `-f` for this command after all.

**Comment by dturn** [comment]
I've added the 1.0 requirement label to this issue. Though 1.0 requirement need not be the `-f` as in the design doc (or current issue name), but answering the concerns raised here and likely keeping support for the functionally that `--template` provides.

**Comment by jessie-JNing** [comment]
>Also its default value is kinda random (`task-runner-template`); should we remove it or change it to something like `krane-run-template`?
 My inclination (not a strong opinion at this time) is to improve the current flag's name, remove its default, and not provide `-f` for this command after all.

From the discussion above, we decide: 
- do NOT provide `-f` for `krane_run` command. 
- rename default template from `task-runner-template` to some better name like `krane-run-template`, or remove default template value. @KnVerey could you share why should remove it? I think it's a non-nullable arg.

**Comment by KnVerey** [comment]
If we remove the default name, the flag would become required.
