### ISSUE TITLE
Update statsd-instrument wrapping code to be compatible with 2.5.0

### ISSUE THREAD

**Issue by dalehamel** [Shopify/kubernetes-deploy#576]
# Bug report

kubernetes-deploy tried to do optimistic versioning for statsd-instrument, but this allowed for it to be bumped to 2.5.0 which is API incompatible. This will cause deploy failures like those in #575 if an app is not using a gemfile to pin the version already. If a bundle update occurs, deploys will fail.

**Expected behavior:**

Deploys should proceed and not fail in the monkey-patched statsd code

**Actual behavior:**

Deploys fail with a stacktrace like:

```
Traceback (most recent call last):
--
  | 11: from /usr/bin/kubernetes-deploy:23:in `<main>'
  | 10: from /usr/bin/kubernetes-deploy:23:in `load'
  | 9: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/exe/kubernetes-deploy:71:in `<top (required)>'
  | 8: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/lib/kubernetes-deploy/options_helper.rb:28:in `with_processed_template_paths'
  | 7: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/exe/kubernetes-deploy:83:in `block in <top (required)>'
  | 6: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/lib/kubernetes-deploy/deploy_task.rb:140:in `run!'
  | 5: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/lib/kubernetes-deploy/statsd.rb:67:in `block in measure_method'
  | 4: from /usr/lib/ruby/gems/2.5.0/gems/kubernetes-deploy-0.27.0/lib/kubernetes-deploy/statsd.rb:37:in `distribution'
  | 3: from /usr/lib/ruby/gems/2.5.0/gems/statsd-instrument-2.5.0/lib/statsd/instrument.rb:462:in `distribution'
  | 2: from /usr/lib/ruby/gems/2.5.0/gems/statsd-instrument-2.5.0/lib/statsd/instrument.rb:373:in `measure'
  | 1: from /usr/lib/ruby/gems/2.5.0/gems/statsd-instrument-2.5.0/lib/statsd/instrument.rb:537:in `collect_metric'
  | /usr/lib/ruby/gems/2.5.0/gems/statsd-instrument-2.5.0/lib/statsd/instrument/backends/udp_backend.rb:110:in `collect_metric': undefined method `<' for nil:NilClass (NoMethodError)


```

**Version(s) affected:**

0.27.0 at least, but probably all versions.

### Steps to Reproduce

Deploy any app that doesn't use a Gemfile.lock, or do a bundle update and try to deploy.

**Comment by dalehamel** [comment]
I should be clear though, getting #575 out fixes the immediate issue, but we still need to port the API forward, which is what this issue is for.

**Comment by dirceu** [comment]
If we move straight to 2.7.0 we can drop (some of?) the monkeypatching: https://github.com/Shopify/statsd-instrument/blob/master/CHANGELOG.md#version-270.

**Comment by dturn** [comment]
Fixed by https://github.com/Shopify/kubernetes-deploy/pull/594, though the new min version is 2.9
