### ISSUE TITLE
Write migration guide. 

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#601]
We need to write a guide that explains how to migrate from `exe/kubernetes-*` to `krane *`.

- Provide mappings for flags that have changed.
- Provide examples of how to deploy global resources
- Provide examples of any breaking changes
- Explain how to install k8s-deploy gem and krane gem.

**Comment by dirceu** [comment]
The initial version was created and we'll update it as needed on individual PRs.
