### ISSUE TITLE
Replace `ENV['REVISION']` with `--revision`

### ISSUE THREAD

**Issue by dirceu** [Shopify/kubernetes-deploy#605]
We missed replacing `ENV['REVISION']` with `--revision`, which was defined in [Krane's design doc](https://docs.google.com/document/d/1oInUsKplYGNWTymPY48xtDCx3x4Cwc-phcEKUkt2v4U/view). It's important to do so before 1.0 because it's technically a breaking change.

**Comment by dturn** [comment]
We marked this as optional in the design doc. How would people feel about just adding a `--revision` flag to the commands that takes priority but still allow the `ENV["REVISION"]` fallback?
