### ISSUE TITLE
kubernetes-restart to supports DaemonSet

### ISSUE THREAD

**Issue by vvuibert** [Shopify/kubernetes-deploy#610]
# Feature request

- [x] If the maintainers agree with the feature as described here, I intend to submit a Pull Request myself.<sup>1</sup>

**Proposal:** patch `kubernetes-restart` to support `DaemonSet` since right now it [only supports deployments](https://github.com/Shopify/kubernetes-deploy/blob/50e7217d98cb98dc4f96fc4e64ecfc5809daa085/lib/krane/restart_task.rb#L100). This would be useful to restart [kafkabridge](https://github.com/Shopify/kafkabridge/blob/6f02aeecc01fe46f8cfdad540f826867d4dce65a/config/deploy/kafkabridge-basic/kafkabridge.yml.erb#L8)

<sup><small>1</small></sup> <sub>This is the quickest way to get a new feature! We reserve the right to close feature requests, even ones we like, if the proposer does not intend to contribute to the feature and it doesn't fit in our current roadmap.</sub>

**Comment by dturn** [comment]
The feature sounds good to us. Adding a new flag to `krane restart` `--daemonsets` and a new kawrg to the task class https://github.com/Shopify/kubernetes-deploy/blob/50e7217d98cb98dc4f96fc4e64ecfc5809daa085/lib/krane/restart_task.rb#L57 would be our recommendation, but we're happy to discuss alternatives. We're also assuming that if you don't pass any flags and rely on annotations both DS & Deployments in a namespace will be restarted.

**Comment by vvuibert** [comment]
@dturn I was able to automate restarting our deamonsets with https://github.com/Shopify/kafkabridge/pull/156/files
