### ISSUE TITLE
Enable per-resource timeout overrides via an annotation

### ISSUE THREAD

**Issue by KnVerey** [Shopify/kubernetes-deploy#63]
Originally suggested in https://github.com/Shopify/kubernetes-deploy/pull/60. See also https://github.com/Shopify/kubernetes-deploy/pull/62. If this pattern works nicely, it could come in handy for other types of overrides (e.g. priority resource identification) as well.

cc @kirs @sirupsen @wvanbergen @DazWorrall

**Comment by sirupsen** [comment]
✨

**Comment by KnVerey** [comment]
Actually, for Deployments specifically (probably what people want to override most of the time?) a more sophisticated version of this already exists as `progressDeadlineSeconds`: 

<image src="https://screenshot.click/2017-03-15--193323_6936z-hjx63.png" width="600px">

The future automatic rollback aspect scares me, as a rollback of a single resource within a Shipit deploy would be really bizarre UX. Hopefully that will be configurable at a level we can control with the deployment script.

In any case, when this parameter is present, we should probably time out based only on the presence of the related status condition.

**Comment by karanthukral** [comment]
Looking into implementing override for deployments using `Progress Deadline Seconds`
