### ISSUE TITLE
K8s 1.6 HorizontalPodAutoscaler is no longer supported in extensions/v1beta1

### ISSUE THREAD

**Issue by dturn** [Shopify/kubernetes-deploy#75]
> HorizontalPodAutoscaler is no longer supported in extensions/v1beta1 version. Use autoscaling/v1 instead. 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#autoscaling-1

This causes us to fail deploys: https://shipit.shopify.io/shopify/k8s-cluster-services/production/deploys/435598

Bug appears to be this line: 
https://github.com/Shopify/kubernetes-deploy/blob/22972eeb193e862b2521cec81e730e7bba9871ea/lib/kubernetes-deploy/runner.rb#L56

**Comment by dturn** [comment]
@ibawt & @dwradcliffe

**Comment by dwradcliffe** [comment]
cc @KnVerey
